services:
  backend:
    build: ./back
    container_name: mi_backend_node
    ports:
      - "8084:8084"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/usr/src/app

  frontend:
    image: nginx:alpine
    container_name: mi_frontend_nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    restart: always







