version: '3.8'

services:
  backend:
    build: ./back                # Carpeta donde está tu backend Node.js
    container_name: mi_backend_node
    ports:
      - "5000:5000"              # Puerto de tu API Node
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - mongo

  frontend:
    image: nginx:alpine          # Nginx como servidor de frontend
    container_name: mi_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./back/default.conf:/etc/nginx/conf.d/default.conf  # ⚡ Usa tu config personalizada
    restart: always

  mongo:
    image: mongo:latest
    container_name: mi_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:





